/*
 * Blink.asm
 *
 *  Created: 8/1/2018 11:54:33 PM
 *   Author: Chris Darcy
 */ 
reset:
	ldi		r16,1<<PB5		;prepare to declare pin 13 for output
	out		DDRB,r16		;do it
	mov		r17,r16			;preserve Pin value for future use
again:
	out		PORTB,r17		;write signal state to pin 13 to affect the blinking
	rcall	delay1s			;kill clock cycles while admiring pin 13
	eor		r17,r16			;toggle signal for pin 13 
	rjmp	again			;repeat...
	
delay1s:
; Generated by delay loop calculator
; at http://www.bretmulvey.com/avrdelay.html
; Delay 16 000 000 cycles
; 1s at 16 MHz

    ldi  r18, 82
    ldi  r19, 43
    ldi  r20, 0
L1: dec  r20
    brne L1
    dec  r19
    brne L1
    dec  r18
    brne L1
    lpm
    nop
	ret